name: Release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  mac:
    uses: ${{ github.action_path }}/.github/workflows/mac.yml@${{ github.action_ref }}
    secrets: inherit

  #windows:
  #  uses: ${{ github.action_path }}/.github/workflows/windows.yml@${{ github.action_ref }}
  #  secrets: inherit

  build:
    #needs: [mac, windows]
    needs: [mac]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: python-3.9.10-nogil-macos.tar.gz

      - uses: actions/download-artifact@v3

      - name: Display structure of downloaded files
        run: ls -R

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            python-3.9.10-nogil-macos.tar.gz
            #python-3.9.10-amd64.exe
