name: Release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  mac:
    uses: colesbury/nogil-actions-test/.github/workflows/mac.yml@main
    secrets: inherit

  windows:
    uses: colesbury/nogil-actions-test/.github/workflows/windows.yml@main
    secrets: inherit

  build:
    needs: [mac, windows]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            Release.txt
            LICENSE
